version: '2'
services:
    minitwitter-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/minitwitter/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=minitwitter
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
